version: "3.9"

services:
  app:
    container_name: flask_app1
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5100:5100"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=mysql1

  db:
    container_name: mysql_db1
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
